<a href="https://colab.research.google.com/github/Rajeeb321123/Machine-learning-Journey/blob/master/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [82]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [83]:
dataset = pd.read_csv('Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [84]:
z = dataset.drop('Purchased', axis=1).values
z

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [85]:
X = dataset.iloc[:,:-1].values # 2D matrix => : is all for all the rows, now of columns :-1 means upperbound is 0 and lowerbound is -1 means from 0 upto not including last element(-1)
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [86]:
labels = dataset.columns.values.tolist()
labels

['Country', 'Age', 'Salary', 'Purchased']

In [87]:
missingValues=[]
for i, column in enumerate(labels[:-1]):
  for j, value in enumerate(X[:,i]):
    if pd.isnull(value):
      print(f"At {j}th index of column {column} is NaN")
      missingValues.append([column, j])

print(f"The number of missing values are: {len(missingValues)}")

At 6th index of column Age is NaN
At 4th index of column Salary is NaN
The number of missing values are: 2


In [88]:
# y = dataset["Purchased"]
y = dataset.iloc[:, -1].values # we didnt used : for column because we dont want range, otherwise it would have been a 2D array but we need 1D
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Taking care of missing data

1. `deleting the row` or data (only for large dataset with very few missing data).
2. `classical methond` average value (mean), median value or most frequent value

In [89]:
# Classical method
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy ="mean")
imputer.fit(X[:, 1:3]) #1:3 => 1 column up to not including 3 (1 to 2) , we excluded first column because it's a string
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Encoding categorical data

### Encoding the Independent Variable

In [90]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])] , remainder='passthrough') # for first column or country column, index = 0 so [0]. remainder='passthrough' so unspecified column arenot dropped: alternative remainder='drop'

X = ct.fit_transform(X)
X = np.array(X) # ct.fi_transform donot return numpy array but later we are going to need numpy array

X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

### Encoding the Dependent Variable

In [91]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y) # we do not need y to be numpy array like X, so we didnt do anything.
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
# this could have don like this aswell: I did this for udemy 24.coding exercise 3
# Importing the necessary libraries
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

# Load the dataset
dataset = pd.read_csv('titanic.csv')

# labels of titanic.csv: [PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked]

# Identify the categorical data
categorical_features = ['Sex', 'Embarked', 'Pclass']

# Implement an instance of the ColumnTransformer class
ct = ColumnTransformer(transformers=[("encoder",OneHotEncoder(),categorical_features)], remainder='passthrough')


# Apply the fit_transform method on the instance of ColumnTransformer
X = ct.fit_transform(dataset)


# Convert the output into a NumPy array
X = np.array(X)


# Use LabelEncoder to encode binary categorical data
le = LabelEncoder()
y = le.fit_transform(dataset["Survived"])



# Print the updated matrix of features and the dependent variable vector
print(X)
print(y)

## Splitting the dataset into the Training set and Test set

In [92]:
from sklearn.model_selection import train_test_split
# random_state=1 is just seed to match the teacher answer with mine
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1 ) # X=feature and y=dependent variable

In [93]:
X_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [94]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [95]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [96]:
y_test

array([0, 1])

## Feature Scaling

1. StandardScaler: Works well for most case

2. Normalization: Used in specific case if the values are normally distributed in most features

In [97]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:]) # we dont want to feature scaling for dummy variable/ one hot encoded values
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [98]:
X_train,

(array([[0.0, 0.0, 1.0, -0.19159184384578545, -1.0781259408412425],
        [0.0, 1.0, 0.0, -0.014117293757057777, -0.07013167641635372],
        [1.0, 0.0, 0.0, 0.566708506533324, 0.633562432710455],
        [0.0, 0.0, 1.0, -0.30453019390224867, -0.30786617274297867],
        [0.0, 0.0, 1.0, -1.9018011447007988, -1.420463615551582],
        [1.0, 0.0, 0.0, 1.1475343068237058, 1.232653363453549],
        [0.0, 1.0, 0.0, 1.4379472069688968, 1.5749910381638885],
        [1.0, 0.0, 0.0, -0.7401495441200351, -0.5646194287757332]],
       dtype=object),)

In [99]:
X_test

array([[0.0, 1.0, 0.0, -1.4661817944830124, -0.9069571034860727],
       [1.0, 0.0, 0.0, -0.44973664397484414, 0.2056403393225306]],
      dtype=object)